export function generatePayload(industry: string): string {
  switch (industry) {
    case "Automotive":
      return `// ============================================================
// MPA SURGICAL PAYLOAD — Automotive
// Generated by Master Plan Architect
// ============================================================
import React, { createContext, useContext, useEffect, useState } from 'react';

// --- Mock WASM Module (PDK Clutch Micro-Friction Engine) ---
const mockWasmEngine = {
  calcClutchFriction: (rpm: number, temp: number): number => {
    // Simulates a WASM call to a Porsche PDK friction model
    const frictionCoeff = 0.0034 * rpm * Math.exp(-0.0001 * temp);
    return parseFloat(frictionCoeff.toFixed(6));
  },
};

// --- 6 Pillars: Automotive ---
interface AutomotivePillars {
  pdkClutchMicroFriction: number;       // Pillar 1: Drivetrain Precision
  mechanicalFuturesPrice: number;       // Pillar 2: Price Certainty Contract
  torqueVectoringBias: number;          // Pillar 3: Dynamic Load Distribution
  oemWarrantyRiskScore: number;         // Pillar 4: Liability Surface
  supplyChainLeadDays: number;          // Pillar 5: Chip & Parts Velocity
  evsRangeDecayIndex: number;           // Pillar 6: Battery Degradation Signal
}

interface AutomotiveMPAContext {
  pillars: AutomotivePillars;
  isLoading: boolean;
  refresh: () => void;
}

const MPAContext = createContext<AutomotiveMPAContext | null>(null);

export function MasterPlanProvider({ children }: { children: React.ReactNode }) {
  const [isLoading, setIsLoading] = useState(true);
  const [pillars, setPillars] = useState<AutomotivePillars>({
    pdkClutchMicroFriction: 0,
    mechanicalFuturesPrice: 0,
    torqueVectoringBias: 0,
    oemWarrantyRiskScore: 0,
    supplyChainLeadDays: 0,
    evsRangeDecayIndex: 0,
  });

  const compute = () => {
    setIsLoading(true);
    // Pillar 1 — PDK Clutch Micro-Friction via mock WASM
    const rpm = 4200 + Math.random() * 1800;
    const engineTemp = 85 + Math.random() * 30;
    const friction = mockWasmEngine.calcClutchFriction(rpm, engineTemp);

    // Pillar 2 — Mechanical Futures Price (USD/unit)
    const basePrice = 48_500;
    const futuresPrice = basePrice * (1 + (Math.random() - 0.48) * 0.06);

    // Pillar 3 — Torque Vectoring Bias (0–1, rear-biased)
    const tvBias = 0.55 + Math.random() * 0.15;

    // Pillar 4 — OEM Warranty Risk Score (0–100)
    const warrantyRisk = Math.floor(12 + Math.random() * 40);

    // Pillar 5 — Supply Chain Lead Days (semiconductor)
    const leadDays = Math.floor(18 + Math.random() * 34);

    // Pillar 6 — EV Range Decay Index (% per 10k miles)
    const decayIndex = parseFloat((1.8 + Math.random() * 1.2).toFixed(3));

    setPillars({
      pdkClutchMicroFriction: friction,
      mechanicalFuturesPrice: parseFloat(futuresPrice.toFixed(2)),
      torqueVectoringBias: parseFloat(tvBias.toFixed(4)),
      oemWarrantyRiskScore: warrantyRisk,
      supplyChainLeadDays: leadDays,
      evsRangeDecayIndex: decayIndex,
    });
    setIsLoading(false);
  };

  useEffect(() => { compute(); }, []);

  return (
    <MPAContext.Provider value={{ pillars, isLoading, refresh: compute }}>
      {children}
    </MPAContext.Provider>
  );
}

export function useMPA(): AutomotiveMPAContext {
  const ctx = useContext(MPAContext);
  if (!ctx) throw new Error('useMPA must be used within <MasterPlanProvider>');
  return ctx;
}`;

    case "Grocery":
      return `// ============================================================
// MPA SURGICAL PAYLOAD — Grocery
// Generated by Master Plan Architect
// ============================================================
import React, { createContext, useContext, useEffect, useState } from 'react';

// --- Mock Weather API (Spoilage Velocity Engine) ---
const mockWeatherAPI = {
  fetchHumidityIndex: async (): Promise<number> => {
    // Simulates a call to a real-time humidity/temp weather service
    await new Promise(r => setTimeout(r, 120));
    return parseFloat((55 + Math.random() * 35).toFixed(2));
  },
};

// --- 6 Pillars: Grocery ---
interface GroceryPillars {
  spoilageVelocity: number;             // Pillar 1: Perishable Decay Rate (%/hr)
  freshnessCertaintyPrice: number;      // Pillar 2: Freshness Contract Price (USD)
  coldChainBreachRisk: number;          // Pillar 3: Refrigeration Failure Probability
  demandSurgeMultiplier: number;        // Pillar 4: Real-Time Demand Signal
  wasteReductionScore: number;          // Pillar 5: ESG Waste Index (0–100)
  supplierReliabilityIndex: number;     // Pillar 6: Farm-to-Shelf Latency Score
}

interface GroceryMPAContext {
  pillars: GroceryPillars;
  isLoading: boolean;
  refresh: () => void;
}

const MPAContext = createContext<GroceryMPAContext | null>(null);

export function MasterPlanProvider({ children }: { children: React.ReactNode }) {
  const [isLoading, setIsLoading] = useState(true);
  const [pillars, setPillars] = useState<GroceryPillars>({
    spoilageVelocity: 0,
    freshnessCertaintyPrice: 0,
    coldChainBreachRisk: 0,
    demandSurgeMultiplier: 0,
    wasteReductionScore: 0,
    supplierReliabilityIndex: 0,
  });

  const compute = async () => {
    setIsLoading(true);

    // Pillar 1 — Spoilage Velocity based on weather humidity
    const humidity = await mockWeatherAPI.fetchHumidityIndex();
    const spoilage = parseFloat((0.12 * (humidity / 100) * 1.8).toFixed(4));

    // Pillar 2 — Freshness Certainty Contract Price
    const freshnessPricePerUnit = parseFloat((2.40 + (humidity / 100) * 1.60).toFixed(2));

    // Pillar 3 — Cold Chain Breach Risk (0–1)
    const breachRisk = parseFloat((0.03 + Math.random() * 0.12).toFixed(4));

    // Pillar 4 — Demand Surge Multiplier
    const surge = parseFloat((1.0 + Math.random() * 0.45).toFixed(3));

    // Pillar 5 — Waste Reduction Score (ESG)
    const wasteScore = Math.floor(60 + Math.random() * 30);

    // Pillar 6 — Supplier Reliability Index (days latency)
    const reliabilityIndex = parseFloat((3.2 + Math.random() * 2.8).toFixed(2));

    setPillars({
      spoilageVelocity: spoilage,
      freshnessCertaintyPrice: freshnessPricePerUnit,
      coldChainBreachRisk: breachRisk,
      demandSurgeMultiplier: surge,
      wasteReductionScore: wasteScore,
      supplierReliabilityIndex: reliabilityIndex,
    });
    setIsLoading(false);
  };

  useEffect(() => { compute(); }, []);

  return (
    <MPAContext.Provider value={{ pillars, isLoading, refresh: compute }}>
      {children}
    </MPAContext.Provider>
  );
}

export function useMPA(): GroceryMPAContext {
  const ctx = useContext(MPAContext);
  if (!ctx) throw new Error('useMPA must be used within <MasterPlanProvider>');
  return ctx;
}`;

    case "Bio-Medical":
      return `// ============================================================
// MPA SURGICAL PAYLOAD — Bio-Medical
// Generated by Master Plan Architect
// ============================================================
import React, { createContext, useContext, useEffect, useState } from 'react';

// --- Mock Genomic Sequencer API ---
const mockGenomicSequencer = {
  sampleProteinFoldScore: (geneId: string): number => {
    // Simulates AlphaFold-style confidence scoring
    const seed = geneId.split('').reduce((a, c) => a + c.charCodeAt(0), 0);
    return parseFloat(((seed % 40) / 100 + 0.55).toFixed(4));
  },
};

// --- 6 Pillars: Bio-Medical ---
interface BioMedicalPillars {
  proteinFoldConfidence: number;        // Pillar 1: Molecular Stability Score (0–1)
  clinicalTrialBurnRate: number;        // Pillar 2: Cost Velocity (USD/day)
  regulatoryApprovalIndex: number;      // Pillar 3: FDA/EMA Pathway Score
  patientCohortDiversityScore: number;  // Pillar 4: Trial Representation Index
  bioreactorYieldEfficiency: number;    // Pillar 5: Manufacturing Output (%)
  ipExpiryRiskScore: number;            // Pillar 6: Patent Cliff Exposure (0–100)
}

interface BioMedicalMPAContext {
  pillars: BioMedicalPillars;
  isLoading: boolean;
  refresh: () => void;
}

const MPAContext = createContext<BioMedicalMPAContext | null>(null);

export function MasterPlanProvider({ children }: { children: React.ReactNode }) {
  const [isLoading, setIsLoading] = useState(true);
  const [pillars, setPillars] = useState<BioMedicalPillars>({
    proteinFoldConfidence: 0,
    clinicalTrialBurnRate: 0,
    regulatoryApprovalIndex: 0,
    patientCohortDiversityScore: 0,
    bioreactorYieldEfficiency: 0,
    ipExpiryRiskScore: 0,
  });

  const compute = () => {
    setIsLoading(true);

    // Pillar 1 — Protein Fold Confidence via mock Genomic Sequencer
    const geneId = \`GENE-\${Math.floor(Math.random() * 9000 + 1000)}\`;
    const foldScore = mockGenomicSequencer.sampleProteinFoldScore(geneId);

    // Pillar 2 — Clinical Trial Burn Rate (USD/day)
    const burnRate = Math.floor(120_000 + Math.random() * 80_000);

    // Pillar 3 — Regulatory Approval Index (0–100, higher = clearer path)
    const regulatoryIdx = Math.floor(40 + Math.random() * 45);

    // Pillar 4 — Patient Cohort Diversity Score (0–1)
    const diversityScore = parseFloat((0.55 + Math.random() * 0.35).toFixed(3));

    // Pillar 5 — Bioreactor Yield Efficiency (%)
    const yieldEff = parseFloat((72 + Math.random() * 18).toFixed(2));

    // Pillar 6 — IP Expiry Risk Score (0–100)
    const ipRisk = Math.floor(10 + Math.random() * 55);

    setPillars({
      proteinFoldConfidence: foldScore,
      clinicalTrialBurnRate: burnRate,
      regulatoryApprovalIndex: regulatoryIdx,
      patientCohortDiversityScore: diversityScore,
      bioreactorYieldEfficiency: yieldEff,
      ipExpiryRiskScore: ipRisk,
    });
    setIsLoading(false);
  };

  useEffect(() => { compute(); }, []);

  return (
    <MPAContext.Provider value={{ pillars, isLoading, refresh: compute }}>
      {children}
    </MPAContext.Provider>
  );
}

export function useMPA(): BioMedicalMPAContext {
  const ctx = useContext(MPAContext);
  if (!ctx) throw new Error('useMPA must be used within <MasterPlanProvider>');
  return ctx;
}`;

    case "Real Estate":
      return `// ============================================================
// MPA SURGICAL PAYLOAD — Real Estate
// Generated by Master Plan Architect
// ============================================================
import React, { createContext, useContext, useEffect, useState } from 'react';

// --- Mock Macro-Economic Feed ---
const mockMacroFeed = {
  fetchTreasuryYield: async (): Promise<number> => {
    // Simulates pulling 10Y Treasury yield from a Bloomberg-style feed
    await new Promise(r => setTimeout(r, 80));
    return parseFloat((3.8 + (Math.random() - 0.5) * 1.2).toFixed(3));
  },
};

// --- 6 Pillars: Real Estate ---
interface RealEstatePillars {
  capRateDeltaSignal: number;           // Pillar 1: Cap Rate Momentum (bps/qtr)
  liquidityAbsorptionPrice: number;     // Pillar 2: Liquidity Contract Price (USD/sqft)
  zoneReclassRisk: number;              // Pillar 3: Zoning Change Probability (0–1)
  tenantFlightRiskScore: number;        // Pillar 4: Lease Churn Index (0–100)
  constructionCostIndex: number;        // Pillar 5: Materials Inflation Score
  mortgageSpreadCompression: number;    // Pillar 6: Debt Cost Signal (bps)
}

interface RealEstateMPAContext {
  pillars: RealEstatePillars;
  isLoading: boolean;
  refresh: () => void;
}

const MPAContext = createContext<RealEstateMPAContext | null>(null);

export function MasterPlanProvider({ children }: { children: React.ReactNode }) {
  const [isLoading, setIsLoading] = useState(true);
  const [pillars, setPillars] = useState<RealEstatePillars>({
    capRateDeltaSignal: 0,
    liquidityAbsorptionPrice: 0,
    zoneReclassRisk: 0,
    tenantFlightRiskScore: 0,
    constructionCostIndex: 0,
    mortgageSpreadCompression: 0,
  });

  const compute = async () => {
    setIsLoading(true);

    // Pillar 1 — Cap Rate Delta Signal (basis points/quarter)
    const treasuryYield = await mockMacroFeed.fetchTreasuryYield();
    const capRateDelta = parseFloat(((treasuryYield - 3.5) * 28).toFixed(2));

    // Pillar 2 — Liquidity Absorption Price (USD per sqft)
    const liquidityPrice = parseFloat((320 + Math.random() * 180).toFixed(2));

    // Pillar 3 — Zoning Reclassification Risk (0–1)
    const zoneRisk = parseFloat((0.04 + Math.random() * 0.22).toFixed(4));

    // Pillar 4 — Tenant Flight Risk Score (0–100)
    const flightRisk = Math.floor(15 + Math.random() * 50);

    // Pillar 5 — Construction Cost Index (100 = baseline 2020)
    const constCostIdx = parseFloat((138 + Math.random() * 24).toFixed(1));

    // Pillar 6 — Mortgage Spread Compression (bps vs 10Y)
    const spreadCompression = parseFloat((treasuryYield * 42 - 12).toFixed(2));

    setPillars({
      capRateDeltaSignal: capRateDelta,
      liquidityAbsorptionPrice: liquidityPrice,
      zoneReclassRisk: zoneRisk,
      tenantFlightRiskScore: flightRisk,
      constructionCostIndex: constCostIdx,
      mortgageSpreadCompression: spreadCompression,
    });
    setIsLoading(false);
  };

  useEffect(() => { compute(); }, []);

  return (
    <MPAContext.Provider value={{ pillars, isLoading, refresh: compute }}>
      {children}
    </MPAContext.Provider>
  );
}

export function useMPA(): RealEstateMPAContext {
  const ctx = useContext(MPAContext);
  if (!ctx) throw new Error('useMPA must be used within <MasterPlanProvider>');
  return ctx;
}`;

    default:
      return `// No payload generated. Please select a valid industry.`;
  }
}
